### ISSUE TITLE
Defining and parsing configuration file

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#21]
Create a basic `.yaml` configuration file called `configurations.yaml` and give it some settings for
- logging, see `config_logger()` in the `nhs.utils` folder for the parameters you can pass in. Change `config_logger()` to take in the new settings instead of hard-coding them in which is the current approach
- [x] `census_path` - path for a FOLDER containing the SA1 census data to load in
- [x] `gnaf_path` - path for a FOLDER containing the GNAF data to load in

Also...
- [x] Add function that reads this file and output a python dictionary with the settings.
- [x] Add a page in the Wiki for `configurations.yaml`, and show a table of the configuration options, a description of what they do, and example value. e.g.

| Option | Description | Example |
| --- | --- | --- |
| `census_path` | Path to a folder containing the SA1 `.psv` census data | `"./path/to/census_data"` |

More settings will be added, do NOT worry about them for now.

**Comment by ctmes** [comment]
Branch [ #23 ](https://github.com/zazwaz12/CITS3200---National-Housing-Simulation/tree/issue-23-allocate-building-coordinates-to-a-sa1-region)

contains this stuff, no wiki yet

Kind of just naturally had to get added because of specifying in files for Issue #23

**Comment by SodaVolcano** [comment]
This is done and more will be added as we progress with the project so I'll close the issue.
