### ISSUE TITLE
Set up `pyright`

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#3]
Set up the `pyright` static type checker by editing `pyproject.toml`, see https://microsoft.github.io/pyright/#/getting-started

**Comment by Reece030130** [comment]
[tool.poetry]
name = "cits3200-project"
version = "0.1.0"
description = "Python packages for the CITS3200 Project"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.3.0"
loguru = "^0.7.2"
pytest = "^8.3.2"
black = "^24.4.2"
matplotlib = "^3.9.1"
cytoolz = "^0.12.3"
ipykernel = "^6.29.5"
fastexcel = "^0.11.5"
jupyter-black = "^0.3.4"
isort = "^5.13.2"
pathos = "^0.3.2"
pyright ="*"(not sure)

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportMissingTypeStubs = true
strict = true
reportUnknownParameterType = true
reportUntypedFunctionDecorator = true
typeCheckingMode = "basic"
pythonVersion = "3.12"
stubPath (TBA)
include = "**/*.py"

**Comment by SodaVolcano** [comment]
For `pyright` you can just `poetry add pyright` and it'll get the latest version

**Comment by ctmes** [comment]
### For compatibility with Issue 2 (code quality)
1. requirements.txt
  - pytest==7.3.1
  - black==23.3.0
  - pyright==1.1.316

2. pyrightconfig.json
 ``{
  "include": [
    "**/*.py"
  ],
  "exclude": [
    "**/node_modules",
    "**/__pycache__"
  ],
  "ignore": [
    "src/oldstuff"
  ],
  "defineConstant": {
    "DEBUG": true
  },
  "strictListInference": true,
  "strictDictionaryInference": true,
  "strictParameterNoneValue": true
}``

**Comment by SodaVolcano** [comment]
btw @ctmes you can reference issues and PRs using hashtags, like #2 ("`#2`"), Reece please translate the relevant part of the `pyrightconfig.json` into the `pyproject.toml` section for pyright
