### ISSUE TITLE
Github Project fix?

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#31]
- [ ] Is there a way to assign new issues to the project by default?
- [ ] Can we remove or rename iteration 1 to iteration 2?
- [ ] Is there a way to auto-link priority with the priority labels?
- [ ] what are those T-shirt sizes :skull:

**Comment by zazwaz12** [comment]
The issue can be assigned automatically if we make an adjustment to the GitHub Action.

Adjusted to iteration 2 and iteration 3 -> aligning with Sprint 2 and Sprint 3 dates.

Similar to assigning the entire issue - we can add to the GitHub actions to automatically link labels.

T-shirt sizes is an industry default across all task trackers - was not something I added. Removed and simplified to just progression tag and priority tag.

Will add this requirement to the GitHub Actions issue.
