### ISSUE TITLE
Set up Github Project Kaban board

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#4]
Do this once the project requirements (WBS) are finalised.

**Comment by zazwaz12** [comment]
Microsoft Planner is was not available to our subgroup, it would have to be with the entire course.
Other solutions in Teams would require further permissions, and the Monday is overkill for our project management.
Proposing to have a live Excel document in Teams chat.

**Comment by zazwaz12** [comment]
GitHub Projects will work, waiting on clarity for scope of work.

**Comment by zazwaz12** [comment]
Hoping to split the Kaban board into requirement based, and then issue based - to encapsulate all aspects of the project.
