### ISSUE TITLE
Add `flake8`

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#40]
I was lazy and forgot to add `flake8`, it's a code linter that adds extra complaint if your code style doesn't conform with PEP8

- [x] Add to `poetry`
- [x] Add to Github Action checks
- [x] Add to pre-commit hooks in `.git/hooks/pre-commit`

Run it with ` --max-complexity=<number>` and choose some number idk

**Comment by ctmes** [comment]
Do I have to make .git/hooks/pre-commit?
Documentation for pre-commit has it in root dir (https://[pre-commit](https://pre-commit.com/).com/)

**Comment by SodaVolcano** [comment]
> Do I have to make .git/hooks/pre-commit?
> Documentation for pre-commit has it in root dir (https://[pre-commit](https://pre-commit.com/).com/)

Yep should run the check before each commit is made to make sure the commits have consistent style
