### ISSUE TITLE
Template fix

### ISSUE THREAD

**Issue by SodaVolcano** [zazwaz12/CITS3200---National-Housing-Simulation#45]
Template for the PR uses "Title: "Closes issue #<number> " which **doesn't close the issue when the PR gets merged**, change wording to "Closes #<number>".

ALso, remove some part of the PR template:
- [x] remove the title, about, labels, and assignees section - I don't think these do anything?
- [x] Change "What does this implement/fix?" to "summary of changes"
- [x] Reduce number of checklist items 
    - remove: self-review, change to documentation, generate no new warnings, dependency change
    - merge the two testing items into one item
    - add type annotation

Also is there a template for issues? A simple template would probably do

**Comment by ctmes** [comment]
There is a template for issues, not entirely sure why it isn't working, will fix by Monday night

**Comment by ctmes** [comment]
There is some stupid issue with maybe github because I do what their documentation says, their error links aren't working, their errors don't exist on their documentation, and it persists.

I will maybe get rid of them all and make one general purpose one.

**Comment by SodaVolcano** [comment]
bleh that sucks, no worries if the issue template is not working since that's more for convenience :+1:
