### ISSUE TITLE
GitHub Actions for linking Issues & Projects

### ISSUE THREAD

**Issue by zazwaz12** [zazwaz12/CITS3200---National-Housing-Simulation#47]
## **Summary**
When adding an issue and the respective priority label - it needs to be mapped to the Project.

## **Steps to Reproduce**
Add a new GitHub Action that maps the priority fields to a priority field in the project & to have it default to the Project.

## **Technical Details**
The new workflow in a .yml configuration.

## **Acceptance Criteria**
- [ ] New Issues in repository automatically add to Project
- [ ] Difficulty label maps towards a difficulty label in Project
- [ ] Task type label maps towards a type label in Project

## **Environment**
**main** branch

## **Proposed Solution**
Addition of another GitHub Action to the workflows folder.

**Comment by SodaVolcano** [comment]
closing this, not important
