### ISSUE TITLE
issue-<57>-<Read_spreadsheet return empty dictionary when using {key} to specify the key value.>

### ISSUE THREAD

**Issue by Reece030130** [zazwaz12/CITS3200---National-Housing-Simulation#57]
# **Bug Summary**
When load lazyframe from a path with {key} in the string. read_spreadsheet function return an empty dict which is not expected. Not sure I used {key} properly.
Function call: 
lf = read_spreadsheets(
        "C:/Users/IamNo/Desktop/DataFiles/FilesIn/census/2021 Census GCP All Geographies for AUS/AUS/2021Census_{key}_AUS_AUS.csv","csv")
![Screenshot 2024-09-02 171314](https://github.com/user-attachments/assets/c6fb7bcb-e48e-40a7-a8fd-b9a80f2287fa)
Function return:
![Screenshot 2024-09-02 171326](https://github.com/user-attachments/assets/efa7aa06-2d4a-4d67-8b1c-b1e10425a806)
Expected:
{'G01': <LazyFrame at 0x280DF538BF0(Random)>, 'G02': <LazyFrame at 0x280DF5387A0>, 'G03': <LazyFrame at 0x280DF5386E0>}.

**Comment by SodaVolcano** [comment]
I'm able to load it correctly:

```python
from nhs.data.handling import read_spreadsheets

path = "DataFiles/FilesIn/census/2021 Census GCP All Geographies for AUS/AUS/2021Census_{key}_AUS_AUS.csv"
read_spreadsheets(path, "csv")
```

output:
```python
{'G01': <LazyFrame at 0x7FD019860620>,
 'G02': <LazyFrame at 0x7FD019860650>,
 'G03': <LazyFrame at 0x7FD019860680>,
 'G04A': <LazyFrame at 0x7FD0198606B0>,
 'G04B': <LazyFrame at 0x7FD0198606E0>,
 'G05': <LazyFrame at 0x7FD019860710>,
 'G06': <LazyFrame at 0x7FD019860740>,
 'G07': <LazyFrame at 0x7FD019860770>,
 'G08': <LazyFrame at 0x7FD0198607A0>,
 'G09A': <LazyFrame at 0x7FD0198607D0>,
 'G09B': <LazyFrame at 0x7FD019860800>,
 'G09C': <LazyFrame at 0x7FD019860830>,
 'G09D': <LazyFrame at 0x7FD019860860>,
 'G09E': <LazyFrame at 0x7FD019860890>,
 'G09F': <LazyFrame at 0x7FD0198608C0>,
 'G09G': <LazyFrame at 0x7FD0198608F0>,
 'G09H': <LazyFrame at 0x7FD019860920>,
 'G10A': <LazyFrame at 0x7FD019860950>,
 'G10B': <LazyFrame at 0x7FD019860980>,
 'G10C': <LazyFrame at 0x7FD0198609B0>
...
```

This might relate to you using Windows path? What do you get when you run this?

```python
from nhs.utils.path import list_files

path = # copy and paste your path here
list_files(os.path.dirname(file_dir_pattern))
```

**Comment by Reece030130** [comment]
Sloved. For windows users. add "//" between Folder and files.
